title: Jean-Marie LEMETAYER
description: Enthusiast embedded systems engineer

baseurl: ""

social:
    gitlab: https://gitlab.com/jmlemetayer
    linkedin: https://www.linkedin.com/in/jmlemetayer
    stackoverflow: https://stackoverflow.com/users/2893600/jml

defaults:
    - scope:
        type: pages
      values:
        layout: default
    - scope:
        type: posts
      values:
        layout: posts
        published: false
        categories: uncategorized

permalink: /:year/:month/:day/:title/

exclude:
    - Gemfile*
    - LICENSE.md
    - README.md
    - icomoon.json

gems:
    - jekyll-feed
    - jekyll-mentions
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

sass:
    style: compressed
