title: Jean-Marie LEMETAYER
description: Enthusiast embedded systems engineer

baseurl: ""
url: https://jml.bzh

social:
    gitlab: https://gitlab.com/jmlemetayer
    linkedin: https://www.linkedin.com/in/jmlemetayer
    stackoverflow: https://stackoverflow.com/users/2893600/jml

disqus: jmlemetayer

defaults:
    - scope:
        type: pages
      values:
        layout: default
    - scope:
        type: posts
      values:
        layout: posts
        published: false
        categories: uncategorized
        comments: true

permalink: /:year/:month/:day/:title/

exclude:
    - Gemfile*
    - LICENSE.md
    - README.md
    - icomoon.json

gems:
    - jekyll-feed
    - jekyll-mentions
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

sass:
    style: compressed

prose:
    media: media
    rooturl: _posts
    siteurl: https://jml.bzh
    metadata:
        _posts:
            - name: layout
              field:
                element: hidden
                value: posts
            - name: title
              field:
                element: text
            - name: categories
              field:
                element: multiselect
                alterable: true
                label: Categories
            - name: tags
              field:
                element: multiselect
                alterable: true
                label: Tags
            - name: comments
              field:
                element: button
                on: Comments enabled
                off: Comments disabled
            - name: published
              field:
                element: button
                on: Publish post
                off: Do NOT publish post
